Delete *MODULE + *PGM before *LIB

diff --git a/strtcpsvr/install_sc_tcpsvr b/strtcpsvr/install_sc_tcpsvr
--- a/strtcpsvr/install_sc_tcpsvr
+++ b/strtcpsvr/install_sc_tcpsvr
@@ -7,8 +7,10 @@ oopsies() {
   echo ''
   echo ''
   echo '-------------------------------------------------------'
-  echo 'Cleaning up from error...'
-  /QOpenSys/usr/bin/system -Kkpiebv "DLTLIB ${SCTARGET}"
+  echo 'Cleaning up from error...'  
+  /QOpenSys/usr/bin/system -Kkpiebv "DLTMOD MODULE(${SCTARGET}/SC)" || echo "module doesn't exist"
+  /QOpenSys/usr/bin/system -Kkpiebv "DLTPGM PGM(${SCTARGET}/SC)" || echo "program doesn't exist"
+  /QOpenSys/usr/bin/system -Kkpiebv "DLTLIB ${SCTARGET}" || echo "library doesn't exist"
   /QOpenSys/usr/bin/system -Kkpiebv "RMVTCPSVR SVRSPCVAL(*SC)" || echo "TCPSVR was not installed"
   echo ''
   echo 'FAILED!!'
